[tool.poetry]
name = "polus-plugins-transforms-images-image-assembler"
version = "1.3.0-dev0"
description = "A scalable image assembler plugin."
authors = ["Nick Schaub <nick.schaub@nih.gov>", "Antoine Gerardin <antoine.gerardin@gmail.com>"]
readme = "README.md"
packages = [{include = "polus", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9.15"
bfio = {version = "2.1.9", extras = ["all"]}
filepattern = "1.4.7"
preadator = "0.3.0.dev1"
typer = "^0.7.0"
pip = "^23.0.1"
install = "^1.3.5"


[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
default = false
secondary = true


[tool.poetry.group.dev.dependencies]
bump2version = "^1.0.1"
flake8 = "^6.0.0"
pre-commit = "^3.2.1"
flake8-docstrings = "^1.7.0"
black = "^23.3.0"
mypy = "^1.1.1"
pytest = "^7.2.2"
ruff = "^0.0.270"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
